# Generated by Django 2.2.4 on 2019-10-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divers', '0002_auto_20191014_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divers',
            name='n_dives',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='divers',
            name='padi_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='divers',
            name='photo',
            field=models.ImageField(upload_to='photo'),
        ),
    ]
