# Generated by Django 2.2.4 on 2019-10-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divers', '0003_auto_20191015_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divers',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
