# Generated by Django 2.2.4 on 2019-12-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divers', '0006_auto_20191228_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courses',
            name='thetype',
            field=models.CharField(choices=[('op', 'openwater'), ('ad', 'advanced')], max_length=50),
        ),
    ]
