# Generated by Django 2.2.4 on 2020-01-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divers', '0007_auto_20191228_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='tourphoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
